<?php
/** @var \Magento\Framework\View\TemplateEngine\Php $this **/
/** @var \MiraklSeller\Sales\Block\Adminhtml\MiraklOrder\Shipment\Create $block */
?>
<script>
    require([
        'mage/template',
        'prototype'
    ], function (mageTemplate) {
        if (trackingControl) {
            trackingControl.add();
            $('track_row_container')
                .select('.action-delete')
                .invoke('hide');
        }
    });
</script>